### ISSUE TITLE
Error when sendig via SES undefined local variable or method `params'

### ISSUE THREAD

**Issue by rwky** [sensu-plugins/sensu-plugins-mailer#25]
```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-mailer-0.3.0/bin/handler-mailer-ses.rb:28:in `prefix_subject': undefined local variable or method `params' for #<Mailer:0x0000000278bbb0> (NameError)
from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-mailer-0.3.0/bin/handler-mailer-ses.rb:55:in `handle'
from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:55:in `block in <class:Handler>'"
```

**Comment by majormoses** [comment]
closed via #31
